spring.application.name=palate-backend
spring.application.name=palate-backend

# Base de datos Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-bitter-poetry-al6bif5m.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7SWfCTt3ONRB
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect